---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution | replace(' ', '') | lower}}-{{ansible_distribution_release | replace(' ', '') | lower}}.yml"
    - "{{ansible_distribution | replace(' ', '') | lower}}.yml"
    - "{{ansible_os_family | replace(' ', '') | lower}}.yml"

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: installing python os pkgs...
  become: yes
  become_user: root
  with_items: '{{python3_pkgs}}'
  package:
    name: '{{item}}'
    state: present

- name: Make python3 system-wide default
  become: yes
  become_user: root
  with_items:
    - s: python{{python3_version | default(3)}}
      d: python
    - s: pip{{python3_version | default(3)}}
      d: pip
  when: python3_set_system_default and not (python3_system_default | default(false))
  alternatives:
    name: "{{item.d}}"
    link: /usr/bin/{{item.d}}
    path: /usr/bin/{{item.s}}
